apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: microservices-blog
build:
  artifacts:
    - image: mini-blog/client
      context: client
      docker:
        dockerfile: Dockerfile
    - image: mini-blog/comments
      context: comments
      docker:
        dockerfile: Dockerfile
    - image: mini-blog/event-bus
      context: event-bus
      docker:
        dockerfile: Dockerfile
    - image: mini-blog/moderation
      context: moderation
      docker:
        dockerfile: Dockerfile
    - image: mini-blog/posts
      context: posts
      docker:
        dockerfile: Dockerfile
    - image: mini-blog/query
      context: query
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - infra/k8s/client.yaml
    - infra/k8s/comments.yaml
    - infra/k8s/event-bus.yaml
    - infra/k8s/ingress-srv.yaml
    - infra/k8s/moderation.yaml
    - infra/k8s/posts.yaml
    - infra/k8s/query.yaml
